<?php
/**
 * Created by PhpStorm.
 * User: ziann
 * Date: 16/3/26
 * Time: 上午12:17
 */

namespace App\Http\Controllers;


use App\Models\Articles;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Metas;
use Illuminate\Support\Facades\Validator;
use Input;
use App\Models\Flags;
use App\Models\SystemLogger;
use Session;

class ArticlesController extends AdminBaseController
{
    use SoftDeletes;
    protected $modelName = 'App\Models\Articles';
    protected $customPath = 'back.article';
    protected $customView = ['index', 'create', 'edit', 'view'];
    protected $dates = ['deleted_at'];
    protected $bCustomCondition = true;
    protected $aCustomConditionArray = ['type' => ['=', 'article']];
    protected $routeName='article';

    public function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub
        $sModel = $this->model;
        $oFlags = Flags::getFlags();
        $this->setVars('flags', $oFlags);
        $categories = Metas::getAllCategories();
        $this->setVars('categories', $categories);
        $this->setVars('_title', __('_basic.articles'));
    }
}