<?php
/**
 * meta控制器,目前暂对catetory支持
 * User: ziann
 * Date: 16/3/27
 * Time: 下午1:25
 */

namespace App\Http\Controllers;


use App\Http\Controllers\AdminBaseController;
use Illuminate\Support\Facades\Validator;
use Request;
use Input;
use App\Models\SystemLogger;
use Session;

class MetasController extends AdminBaseController
{

    protected $modelName = 'App\Models\Metas';
    protected $customPath = 'back.meta';
    protected $customView = ['index', 'create', 'edit', 'view'];
    protected $bCustomCondition = true;
    protected $aCustomConditionArray = ['type' => ['=', 'category']];
    protected $routeName='category';

    public function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub
        $sModel = $this->model;
        $this->setVars('_title', __('_basic.category'));
    }
}