<?php
/**
 * Created by PhpStorm.
 * User: ziann
 * Date: 16/3/26
 * Time: 上午12:17
 */

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Validator;
use Request;
use Input;
use Cache;
use Session;
use App\Models\Permission;
use App\Models\SystemLogger;

class PermissionController extends AdminBaseController
{
    protected $modelName = 'App\Models\Permission';
    protected $customPath = 'back.permission';
    protected $customView = ['index', 'create', 'edit', 'view',];
    protected $routeName = 'permission';
/*    protected $bCustomCondition = true;//页面前提条件是否开启
    protected $aCustomConditionArray = [];// 分配到页面的数据数组*/

    public function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub
        $sModel = $this->model;
        $this->setVars('types',$sModel::$permissionType);
        $this->setVars('_title', __('_user.permission'));
    }
}