<?php
/**
 * Created by PhpStorm.
 * User: zero
 * Date: 16-4-9
 * Time: 下午1:52
 */

namespace App\Http\Controllers;

use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\User;

class SystemLoggerController extends AdminBaseController
{

    use SoftDeletes;
    protected $dates=['deleted_at'];
    protected $modelName='App\Models\SystemLogger';
    protected $customPath='back.system_log';
    protected $customView=['index','view'];

    public function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub
        $this->setVars('userType',User::$userType);
        $this->setVars('_title', __('_log.log'));
    }

    /** [浏览日志详情]
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse|mixed
     */
    public function view($id)
    {
        if (!$id) {
            return $this->goBack('error', __('_basic.visit-error'));
        }
        $sModel = $this->model;
        $oLogger = $sModel::find($id);
        if (!is_object($oLogger)) {
            return $this->goBack('error', __('_log.log-error'));
        }
        $this->setVars('sys_log', $oLogger);
        return $this->render();
    }
}