<?php
/**
 * Created by PhpStorm.
 * User: zero
 * Date: 16-3-28
 * Time: 下午1:52
 */

namespace App\Http\Controllers;

use Auth;
use Input;
use Cache;

class SystemOptionsController extends AdminBaseController
{
    protected $customPath = 'back.syscfg';
    protected $customView = [
        'index',
    ];
    protected $modelName = 'App\Models\SystemOptions';
    protected $bExtraSearch = false;
    protected $routeName = 'syscfg';

    public function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub
        $this->setVars('oUser', Auth::user());
        $this->setVars('_title', __('_basic.syscfg'));
    }

    /**
     * [系统配置写入缓存，永久缓存]
     * @return mixed
     */
    public function index()
    {
        if (Cache::has('syscfg')) {
            $data = Cache::get('syscfg');
        } else {
            $oSyscfg = $this->model->all();
            $data = [];
            foreach ($oSyscfg as $syscfg) {
                $data[$syscfg->name] = $syscfg->value;
            }
            Cache::forever('syscfg',$data);
        }
        $this->setVars('data', $data);
//        pr($datas);exit;
        return $this->render();
    }

    public function edit()
    {
//        pr(Input::all());exit;
        $aData=trimArray(Input::all());
        $bSucc=$this->model->save($aData);
        if($bSucc){
            Cache::forever('syscfg',$aData['data']);
            return route()->to('syscfg.index')->withInput()->withError('success',__('_system.system-option-edit-success'));
        }else{
            return route()->to('syscfg.index')->withInput()->withError('error',__('_system.system-option-edit-error'));
        }
    }
}