<?php
/**
 * Created by PhpStorm.
 * User: ziann
 * Date: 16/3/26
 * Time: 上午12:17
 */

namespace App\Http\Controllers;


use Illuminate\Database\Eloquent\SoftDeletes;

class ArticlesController extends AdminBaseController
{
    use SoftDeletes;
    protected $modelName = 'App\Models\Articles';
    protected $customPath = 'articles';
    protected $customViews = ['index', 'create', 'edit'];
    protected $dates = ['deleted_at'];

    public function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub
        $sModel=$this->model;
        $this->setVars('myTitle',__('_basic.articles'));
        $this->setVars('category',$sModel::$getCategory);
    }

    public function edit($id){
        if(!$id){
            return $this->goBack('error',__('_basic.visit-error'));
        }
        $sModel=$this->model;
        $oArticle=$sModel::find($id);
        if(!is_object($oArticle)){
            return $this->goBack('error',__('_basic.article-error'));
        }
        if($this->request->isMethod('POST')){
            
        }
        return $this->render();
    }

}